### ISSUE TITLE
Version 5.0

### ISSUE THREAD

**Issue by formigadiablo** [jcatrysse/redmine_issue_todo_lists2#1]
Does it work for 5.0? I have tried to install it but I had problems when trying to add issues

**Comment by jcatrysse** [comment]
It should but I haven't done extensive testing. Could you please send me the error from the log and some info about what you were doing?

**Comment by jcatrysse** [comment]
> Does it work for 5.0? I have tried to install it but I had problems when trying to add issues

I just did some testing and for me, it seems to work fine, but send me some details and I will look.

**Comment by jcatrysse** [comment]
Ah I see. It's because you are missing the RedmineUp Reporter plugin or any other plugin depending on liquid for that matter. I didn't think about that… I will resolve that issue when I'm back at work in two weeks.

I'll let you know when it's resolved.

I think that installing that RedmineUp reporter plugin will solve it for now.

**Comment by jcatrysse** [comment]
Could you please test? I have no way of testing myself for the moment.

**Comment by formigadiablo** [comment]
Okay! Will try it during today

**Comment by formigadiablo** [comment]
Oh I cannot try it as that plugin is not free.

**Comment by jcatrysse** [comment]
I have made some code changes using my phone. Pull the code again from master and try as it is. I all goes well, I resolved the issue, so you don't need that plugin anymore.

**Comment by formigadiablo** [comment]
Unfortunately is still not working :( 

But thanks a lot for your dedication

**Comment by jcatrysse** [comment]
If you send me a log with errors, I will check furter. You can find the logs under the Redmine directory: logs/production.log

Or try on your development environment if you have one. There the error will be printed on screen.

**Comment by jcatrysse** [comment]
I made some changes in version 2.1.4 for another user having the same issue. Please check if this resolved your issue or send me some error logs / messages.
