### ISSUE TITLE
An error occurs when editing the Issue To-do Lists Plugin.

### ISSUE THREAD

**Issue by damduck01** [jcatrysse/redmine_issue_todo_lists2#4]
Redmine version: 5.0.5.stable
Issue To-do Lists Plugin version: 2.1.2

All functions work normally, but when saving after editing the To-do list, a 500 Internal error occurs.

The relevant error log is:

NoMethodError (undefined method `update_at
tributes' for #<IssueTodoList:0x0000557db1a8ece0>
Did you mean? update_attribute):

plugins/redmine_issue_todo_lists2/app/cont
rollers/issue_todo_lists_controller.rb:62:in `block in update'

plugins/redmine_issue_todo_lists2/app/cont
rollers/issue_todo_lists_controller.rb:61:in `update'

lib/redmine/sudo_mode.rb:61:in `sudo_mode'

Can you answer me how to solve it?

**Comment by jcatrysse** [comment]
I'll have a look, but I can't test for the moment. So I will need you to do so.

**Comment by jcatrysse** [comment]
> Can you answer me how to solve it?

I made a new branch 2.1.3 with a possible solution, but this is to be tested. Could you checkout that new branch and test it?

#5

**Comment by jcatrysse** [comment]
I don't have Rails 6.1 at hand, but I presume this should be functional now. Leave a note if it isn't.

**Comment by damduck01** [comment]
2.1.3 After installation, the test result is normal.
Thank you.
