### ISSUE TITLE
In a new issue, it is not possible to deselect after selecting in the To-do lists selection.

### ISSUE THREAD

**Issue by damduck01** [jcatrysse/redmine_issue_todo_lists2#6]
Redmine version: 5.0.5.stable
Issue To-do Lists Plugin version: 2.1.2

In a new issue, it is not possible to deselect after selecting in the To-do lists selection.
Functionality needs to be improved to enable release.
Right now, we are using it as a process of deregistering again after registration.

**Comment by jcatrysse** [comment]
Could you elaborate on what you are doing? I'm not sure to understand what you are saying.

When creating a new issue, or editing an existing issue, to-do lists can be deselected using the ctrl + click in the selection box.

Be aware that the user must have "remove from list" privileges.

Once an issue has been created, it is also possible to add/remove it from a to-do list:
1. Directly from the to-do list.
2. From the issues context menu (right click)
3. From the issue's details view, in the right pane (clicking the link / unlink)
4. While editing the issue (unselect the lists)

**Comment by jcatrysse** [comment]
I verified, and also when manually adding new issues to a list, it can be removed:
1. Click the unlink icon
2. Use the context menu

Are you sure the "remove" privilege has been set?

Please provide some screenshots for my better understanding.

**Comment by damduck01** [comment]
Thanks for your answer. It can be released with Ctrl + Left Click.

**Comment by jcatrysse** [comment]
Great!
